name: Scrape

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  scrape:
    strategy:
      matrix:
        state:
          [
            AL,
            AK,
            AZ,
            AR,
            CA,
            CO,
            CT,
            DE,
            FL,
            GA,
            HI,
            ID,
            IL,
            IN,
            IA,
            KS,
            KY,
            LA,
            ME,
            MD,
            MA,
            MI,
            MN,
            MS,
            MO,
            MT,
            NE,
            NV,
            NH,
            NJ,
            NM,
            NY,
            NC,
            ND,
            OH,
            OK,
            OR,
            PA,
            RI,
            SC,
            SD,
            TN,
            TX,
            UT,
            VT,
            VA,
            WA,
            WV,
            WI,
            WY,
          ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout data
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.state }}
          path: data
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install warn-scraper
      - name: Run scrapers
        env:
          STATE: ${{ matrix.state }}
        run: |-
          mkdir -p data/files || true
          mkdir -p data/logs || true
          warn-scraper ${{ env.STATE }} --data-dir data --cache-dir data/files --log-level DEBUG
          find /home/runner/.warn-scraper/ || true
          cp /home/runner/.warn-scraper/logs/* data/logs/ || true
      - name: Commit and push
        env:
          STATE: ${{ matrix.state }}
        run: |-
          cd ./data
          git config user.name "WARN scraper bot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "${{ env.STATE }} ${timestamp}" || exit 0
          git push
