name: Scrape

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  scrapers:
    runs-on: ubuntu-latest
    outputs:
      scrapers: ${{ steps.list.outputs.scrapers }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install pipenv
        run: pipx install pipenv
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pipenv'
      - run: pipenv install
      - id: list
        name: List scrapers
        run: echo ::set-output name=scrapers::[\"$(pipenv run python cli.py --list | sed 's/,/","/g')\"]
  scrape:
    needs: scrapers
    strategy:
      fail-fast: false
      matrix:
        scraper: ${{fromJson(needs.scrapers.outputs.scrapers)}}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Checkout data
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.scraper }}
          path: data
      - name: Install pipenv
        run: pipx install pipenv
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pipenv'
      - run: pipenv install
      - name: Clear logs
        run: |
          rm -rf data/logs || true
          mkdir -p data/logs || true
      - name: Replay scraping
        if: ${{ github.event_name == 'push' }}
        env:
          SCRAPER: ${{ matrix.scraper }}
          LOGLEVEL: DEBUG
        run: |-
          pipenv run python cli.py ${{ env.SCRAPER }}
          ! cp /home/runner/.warn-scraper/logs/* data/logs/
      - name: Live scrape
        if: ${{ github.event_name != 'push' }}
        env:
          SCRAPER: ${{ matrix.scraper }}
          LOGLEVEL: DEBUG
        run: |-
          pipenv run python cli.py ${{ env.SCRAPER }} --record-mode all
          ! cp /home/runner/.warn-scraper/logs/* data/logs/
      - name: Commit and push
        env:
          SCRAPER: ${{ matrix.scraper }}
        if: always()
        run: |-
          cd ./data
          git config user.name "WARN scraper bot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "${{ env.SCRAPER }} - ${timestamp}" || exit 0
          git push origin ${{ env.SCRAPER }}
